In [4]:
import torch
print(torch.__version__)

1.4.0


In [5]:
x = torch.empty(4, 3)
print(x)
y = torch.rand(4, 3)
print(y)
z = torch.zeros(4, 3)
print(z)
xx = torch.tensor([[5.5, 2], [4, 4], [5, 5]])
print(xx)

tensor([[1.9432e-19, 1.8390e+25, 1.9346e-19],
        [7.3909e+22, 1.5986e+34, 1.1626e+27],
        [8.9666e-33, 1.3563e-19, 1.8578e-01],
        [3.9177e-02, 4.7429e+30, 5.5272e+31]])
tensor([[0.9921, 0.5225, 0.1617],
        [0.4690, 0.2504, 0.4426],
        [0.3112, 0.8051, 0.5572],
        [0.3202, 0.6927, 0.1051]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[5.5000, 2.0000],
        [4.0000, 4.0000],
        [5.0000, 5.0000]])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.double)
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.8305, -0.3083,  0.3470],
        [-0.0136, -0.0527, -0.2404],
        [-0.3606,  2.0276,  0.4898],
        [-0.1182,  1.3824,  2.0509],
        [ 0.6822,  0.5540,  0.0027]], dtype=torch.float64)
torch.Size([5, 3])


In [7]:
#　标准均匀分布
y = torch.rand_like(x, dtype=torch.double)
#　标准正态分布
z = torch.randn_like(x, dtype=torch.double)
print(x, '\n', y)

tensor([[ 1.8305, -0.3083,  0.3470],
        [-0.0136, -0.0527, -0.2404],
        [-0.3606,  2.0276,  0.4898],
        [-0.1182,  1.3824,  2.0509],
        [ 0.6822,  0.5540,  0.0027]], dtype=torch.float64) 
 tensor([[0.1498, 0.9018, 0.8314],
        [0.5947, 0.3928, 0.3350],
        [0.5778, 0.0913, 0.2488],
        [0.3022, 0.5480, 0.6777],
        [0.2924, 0.7014, 0.8706]], dtype=torch.float64)


In [8]:
# 加法
y = torch.rand(5, 3, dtype=torch.double)
print(x, '\n', y)
print(x + y)
print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# 任何使张量会发生变化的操作都有一个前缀'_'
y.add_(x)
print(y)

tensor([[ 1.8305, -0.3083,  0.3470],
        [-0.0136, -0.0527, -0.2404],
        [-0.3606,  2.0276,  0.4898],
        [-0.1182,  1.3824,  2.0509],
        [ 0.6822,  0.5540,  0.0027]], dtype=torch.float64) 
 tensor([[0.9481, 0.5242, 0.9490],
        [0.9678, 0.8324, 0.5089],
        [0.6318, 0.1144, 0.7257],
        [0.7907, 0.4431, 0.1664],
        [0.6330, 0.7538, 0.1193]], dtype=torch.float64)
tensor([[2.7786, 0.2158, 1.2960],
        [0.9543, 0.7797, 0.2685],
        [0.2712, 2.1420, 1.2155],
        [0.6724, 1.8255, 2.2173],
        [1.3152, 1.3078, 0.1220]], dtype=torch.float64)
tensor([[2.7786, 0.2158, 1.2960],
        [0.9543, 0.7797, 0.2685],
        [0.2712, 2.1420, 1.2155],
        [0.6724, 1.8255, 2.2173],
        [1.3152, 1.3078, 0.1220]], dtype=torch.float64)
tensor([[2.7786, 0.2158, 1.2960],
        [0.9543, 0.7797, 0.2685],
        [0.2712, 2.1420, 1.2155],
        [0.6724, 1.8255, 2.2173],
        [1.3152, 1.3078, 0.1220]])
tensor([[2.7786, 0.2158, 1.2960],
        [0

In [9]:
x = torch.rand(6, 6)
# 改变一个 tensor 的大小或者形状
y = x.view(36)
z = x.view(-1, 18)  # -1 表示由另一个维度决定
zz = x.view(-1, 9)
print(x.size(), '\n', y.size(), '\n', z.size(), '\n', zz.size())

torch.Size([6, 6]) 
 torch.Size([36]) 
 torch.Size([2, 18]) 
 torch.Size([4, 9])


In [10]:
# 使用.item()来获得元素tensor的value
print(x[3,3])
print(x[3, 3].item())

tensor(0.4901)
0.490146279335022
